USE bdAlmoxarifado

---PRODUTO
CREATE TABLE PRODUTO (
IdProd INT IDENTITY (1,1) PRIMARY KEY ,
DescricaoProd VARCHAR (100) NOT NULL ,
UnidadeDeMedida VARCHAR (100) NOT NULL,
EstoqueAtual FLOAT (2) DEFAULT '0.00',
EPermanente BIT DEFAULT 0,
IdCategoria INT NULL
)

ALTER TABLE PRODUTO
ADD FOREIGN KEY (IdCategoria) REFERENCES CATEGORIA(Codigo);

---FORNECEDOR 

CREATE TABLE FORNECEDOR (
IdForn INT IDENTITY (1,1) PRIMARY KEY,
NomeForn VARCHAR (100) ,
EndereçoForn VARCHAR (100)
)
 
---SECRETARIA

CREATE TABLE SECRETARIA (
IdSec INT IDENTITY (1,1) PRIMARY KEY,
NomeSec VARCHAR (100)
)

---ENTRADA 

CREATE TABLE ENTRADA (
IdEnt INT IDENTITY (1,1) PRIMARY KEY,
IdForn INT NULL,
DataEntrada DATETIME NOT NULL
)

ALTER TABLE ENTRADA
ADD FOREIGN KEY (IdForn) REFERENCES FORNECEDOR(IdForn);


---SAIDA 

CREATE TABLE SAIDA (
IdSaida INT IDENTITY (1,1) PRIMARY KEY,
IdSec INT NULL,
DataSaida DATETIME NOT NULL
)
ALTER TABLE SAIDA
ADD FOREIGN KEY (IdSec) REFERENCES SECRETARIA (IdSec);

---ITENENTRADA

CREATE TABLE ITENENTRADA (
IdItenEntrada INT IDENTITY (1,1) PRIMARY KEY,
IdEnt INT NULL
)
ALTER TABLE ITENENTRADA
ADD FOREIGN KEY (IdEnt) REFERENCES  ENTRADA (IdEnt);

ALTER TABLE ITENENTRADA
ADD FOREIGN KEY (IdProd) REFERENCES  PRODUTO (IdProd);
ADD IdProd INT NULL



---ITENSAIDA

CREATE TABLE ITENSAIDA (
IdItenSaida INT IDENTITY (1,1) PRIMARY KEY,
IdSaida INT NULL
)

ALTER TABLE ITENSAIDA
ADD FOREIGN KEY (IdProd) REFERENCES  PRODUTO (IdProd);


ALTER TABLE ITENSAIDA
ADD FOREIGN KEY (IdSaida) REFERENCES SAIDA (IdSaida);